{{- if not .Values.elasticsearch.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trivy-operator-elastic-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trivy-operator-elastic-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.elasticsearch.username }}
  username: {{ .Values.elasticsearch.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.elasticsearch.password }}
  password: {{ .Values.elasticsearch.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.elasticsearch.apiKey }}
  apiKey: {{ .Values.elasticsearch.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.elasticsearch.cloudId }}
  cloudId: {{ .Values.elasticsearch.cloudId | b64enc | quote }}
  {{- end }}
{{- end }}
