apiVersion: v2
name: trivy-operator-ecs-exporter
description: A Helm chart for exporting Trivy Operator reports to Elasticsearch in ECS format
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - trivy
  - security
  - elasticsearch
  - kubernetes
maintainers:
  - name: Trivy Operator GUI Team
home: https://github.com/trivy-operator-gui/trivy-operator-gui
sources:
  - https://github.com/trivy-operator-gui/trivy-operator-gui
